# Generated by Django 5.0 on 2024-01-03 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0002_alter_custom_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_product',
            old_name='Post_Description',
            new_name='Product_Description',
        ),
        migrations.RenameField(
            model_name='post_product',
            old_name='Post_Image',
            new_name='Product_Image',
        ),
        migrations.RenameField(
            model_name='post_product',
            old_name='Post_Title',
            new_name='Product_Title',
        ),
        migrations.RemoveField(
            model_name='post_product',
            name='views',
        ),
    ]
