# Generated by Django 5.0 on 2024-01-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0007_cart_cartitem_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
