# Generated by Django 5.0 on 2024-01-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0009_cartitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_product',
            name='category',
            field=models.CharField(choices=[('none', 'None'), ('vegetables', 'Vegetables'), ('fishes', 'Fishes'), ('meats', 'Meat'), ('fruits', 'Fruits')], default='none', max_length=20),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
