# Generated by Django 5.0 on 2024-01-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0010_alter_post_product_category_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_product',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fishes', 'Fishes'), ('meats', 'Meat'), ('fruits', 'Fruits')], default='none', max_length=20),
        ),
    ]
