# Generated by Django 5.0 on 2024-01-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0011_alter_post_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='farm_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='nid_photo',
            field=models.ImageField(blank=True, null=True, upload_to='nid_photos/'),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='present_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
