# Generated by Django 5.0 on 2024-01-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0012_custom_user_farm_area_custom_user_nid_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
