# Generated by Django 5.0 on 2024-01-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0013_custom_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
