# Generated by Django 5.0 on 2024-01-13 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0014_custom_user_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom_user',
            old_name='farm_area',
            new_name='farm_area_adress',
        ),
    ]
