# Generated by Django 5.0 on 2024-01-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0017_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='nid_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/nid_photos'),
        ),
    ]
