# Generated by Django 5.0 on 2024-01-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0018_alter_custom_user_nid_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='Shop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
