# Generated by Django 5.0 on 2024-01-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0019_custom_user_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='user_type',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('user', 'User'), ('agent', 'Agent'), ('admin', 'Admin'), ('seller', 'Seller')], max_length=120),
        ),
    ]
